Changes for 1.3.0

diff --git a/reference/interstitial-init-on-b3 b/reference/interstitial-init-on-b3
--- a/reference/interstitial-init-on-b3
+++ b/reference/interstitial-init-on-b3
@@ -1,12 +1,18 @@
 #!/bin/busybox sh
-# Patch, then kexec, a standard archlinuxarm kernel on an Excito B3.
-# Copyright (c) 2015 sakaki <sakaki@deciban.com>
+# Attempt to mount boot partition and source KSCRIPT within it.
+# Copyright (c) 2016 sakaki <sakaki@deciban.com>
 # License: GPL 3.0+
 # NO WARRANTY
 
 # Simple init script to source /boot/kexec.sh
 # (the sourced script should setup and then kexec -e the final
 # target kernel)
+# If an error occurs, starts recovery console
+
+BOOT_PATH="/dev/sda1"
+DELAY=5
+# We will try and exec the following script on the boot partition
+KSCRIPT="/boot/kexec.sh"
 
 show_red_led() {
     # turn off green and blue LEDs
@@ -17,29 +23,44 @@ show_red_led() {
         /sys/class/leds/bubba3\:red\:error/brightness
 }
 
+start_mini_udev() {
+    echo "Starting mini udev..."
+    echo "/sbin/mdev" > /proc/sys/kernel/hotplug
+    mdev -s
+}
+
+error_exit() {
+    # light the red led
+    show_red_led
+    echo "Starting recovery shell on serial console..." >&2
+    exec /bin/busybox sh -i
+}
+
 # Mount the /proc and /sys filesystems.
 /bin/busybox mount -t proc none /proc
 /bin/busybox mount -t sysfs none /sys
 /bin/busybox mount -t devpts none /dev/pts
+
 # ensure all symlinks are present
 /bin/busybox --install -s
 
-BOOT="/dev/sda1"
-DELAY=0
-
-KSCRIPT="/boot/kexec.sh"
-
+# start udev
+start_mini_udev
 sleep "${DELAY}"
-echo "Mounting boot filesystem (read only)..."
-mount -o ro "${BOOT}" /boot
 
+echo "Mounting boot filesystem (read only)..."
+if ! mount -o ro "${BOOT_PATH}" /boot; then
+    echo "Error - failed to mount ${BOOT_PATH}!" >&2
+    error_exit
+fi
 if [ -f "${KSCRIPT}" ]; then
     echo "Sourcing ${KSCRIPT}..."
     source "${KSCRIPT}"
 else
     echo "Error - ${KSCRIPT} not found!" >&2
-    # light the red led
-    show_red_led
-    echo "Starting recovery shell on serial console..."
-    exec /bin/busybox sh -i
+    error_exit
 fi
+# should not get here, KSCRIPT should have kexec'd a new kernel
+echo "Error - ${KSCRIPT} has returned!" >&2
+error_exit
+
